server:
  port: 8000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # sql 예쁘게 출력
        default_batch_fetch_size: 1000
    show-sql: true  # sql 출력
    generate-ddl: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

portal:
  id: ENC(BbLrqZ2Jjx9f7hI6w5HDCJjeDvlNk7yD)
  pwd: ENC(Kxbc19YJRcpWi2fvhPxHCVazoY6AKj9W)