server:
  port: 8000
  servlet:
    context-path: /

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

portal:
  id: ENC(BbLrqZ2Jjx9f7hI6w5HDCJjeDvlNk7yD)
  pwd: ENC(Kxbc19YJRcpWi2fvhPxHCVazoY6AKj9W)
  year: ENC(utnocw5+PhD7OaXVgGjhYA==) # 연도
  shtm: ENC(A+tf8XBFmW2pQn7SOpjgOQ==) # 학기 구분

