spring:

  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # sql 예쁘게 출력
        default_batch_fetch_size: 1000
    show-sql: true  # sql 출력
    generate-ddl: true

  h2:
    console:
      enabled: true
      path: /h2-console

#
#  jpa:
#    hibernate:
#      ddl-auto: create
