server:
  port: 8000
  servlet:
    context-path: /

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

portal:
  id: ENC(Z6HpAscjxxVoGxEdwr1P3w==)
  pwd: ENC(Lzc6O4kHIQDx5IfHFjhYsJlhXKuxPaJJ)
  year: ENC(utnocw5+PhD7OaXVgGjhYA==) # 연도
  shtm: ENC(A+tf8XBFmW2pQn7SOpjgOQ==) # 학기 구분

