jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

portal:
  id: ${PORTAL_ID}
  pwd: ${PORTAL_PWD}

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.type: trace